# # Create users:
# me = User.create(username: "annabush092@gmail.com", first_name: "Anna")
# natalie = User.create(username: "natalie@natalie.com", first_name: "Natalie")
# david = User.create(username: "david@david.com", first_name: "David")
# christina = User.create(username: "christina@christina.com", first_name: "Christina")
#
# # Create families:
# woodwind = Family.create(name: "Woodwind")
# string = Family.create(name: "String")
# brass = Family.create(name: "Brass")
# percussion = Family.create(name: "Percussion")
# keyboard = Family.create(name: "Keyboard")
# plucked = Family.create(name: "Plucked String")
# voice = Family.create(name: "Vocal")
# electric = Family.create(name: "Electronic")
# intellect = Family.create(name: "Intellect")
# other = Family.create(name: "Other")
#
# # Create genres:
# Genre.create(name: "Western Classical")
# Genre.create(name: "Jazz")
# Genre.create(name: "Symphonic")
# Genre.create(name: "String Quartet")
# Genre.create(name: "Chamber Ensemble")
# Genre.create(name: "Contemporary Music")
# Genre.create(name: "Pop")
# Genre.create(name: "Texas Country")
# Genre.create(name: "Country")
# Genre.create(name: "Bluegrass")
# Genre.create(name: "Zydeco")
# Genre.create(name: "Dixiland")
# Genre.create(name: "Rap")
# Genre.create(name: "K-Pop")
# Genre.create(name: "Rock")
# Genre.create(name: "Indie Rock")
# Genre.create(name: "Singer-songwriter")
#
# #Create instruments:
# Instrument.create(name: "Piccolo", family_id: woodwind.id)
# Instrument.create(name: "Flute", family_id: woodwind.id)
# ebclari = Instrument.create(name: "Eb Clarinet", family_id: woodwind.id)
# bbclari = Instrument.create(name: "Bb Clarinet", family_id: woodwind.id)
# aclari = Instrument.create(name: "A Clarinet", family_id: woodwind.id)
# Instrument.create(name: "Bass Clarinet", family_id: woodwind.id)
# Instrument.create(name: "Oboe", family_id: woodwind.id)
# Instrument.create(name: "English Horn", family_id: woodwind.id)
# Instrument.create(name: "Bassoon", family_id: woodwind.id)
# Instrument.create(name: "Contra Bassoon", family_id: woodwind.id)
# Instrument.create(name: "French Horn", family_id: brass.id)
# Instrument.create(name: "Trumpet", family_id: brass.id)
# Instrument.create(name: "Coronet", family_id: brass.id)
# Instrument.create(name: "Trombone", family_id: brass.id)
# Instrument.create(name: "Bass Trombone", family_id: brass.id)
# Instrument.create(name: "Euphonium", family_id: brass.id)
# Instrument.create(name: "Tuba", family_id: brass.id)
# Instrument.create(name: "Violin", family_id: string.id)
# Instrument.create(name: "Viola", family_id: string.id)
# Instrument.create(name: "Cello", family_id: string.id)
# Instrument.create(name: "Double Bass", family_id: string.id)
# Instrument.create(name: "Timpani", family_id: percussion.id)
# Instrument.create(name: "Drumset", family_id: percussion.id)
# Instrument.create(name: "Orchestral Percussion", family_id: percussion.id)
# Instrument.create(name: "Mallet Percussion", family_id: percussion.id)
# Instrument.create(name: "Marimba", family_id: percussion.id)
# Instrument.create(name: "Acoustic Guitar", family_id: plucked.id)
# Instrument.create(name: "Electric Guitar", family_id: plucked.id)
# Instrument.create(name: "Mandolin", family_id: plucked.id)
# Instrument.create(name: "Banjo", family_id: plucked.id)
# piano = Instrument.create(name: "Piano", family_id: keyboard.id)
# Instrument.create(name: "Organ", family_id: keyboard.id)
# Instrument.create(name: "Composer", family_id: intellect.id)
# Instrument.create(name: "Conductor", family_id: intellect.id)
# Instrument.create(name: "Voice", family_id: voice.id)
# Instrument.create(name: "Soprano", family_id: voice.id)
# Instrument.create(name: "Contralto", family_id: voice.id)
# Instrument.create(name: "Tenor", family_id: voice.id)
# Instrument.create(name: "Bass", family_id: voice.id)
# Instrument.create(name: "Electric Bass", family_id: plucked.id)
#
# # Add associations
me = User.find_by(username: "annabush092@gmail.com")
# natalie = User.find_by(username: "natalie@natalie.com")
# david = User.find_by(username: "david@david.com")
# christina = User.find_by(username: "christina@christina.com")
bbclari = Instrument.find_by(name: "Bb Clarinet")
classic = Genre.find_by(name: "Western Classical")

#
# me.update(instruments: [piano, ebclari, bbclari, aclari])
# me.add_contacts([david, natalie, christina])
me.add_skill({instrument: bbclari, genre: classic, teach: true, perform: true})
