# # Create users:
# me = User.create(username: "annabush092@gmail.com", first_name: "Anna", last_name: "Bush", password: "a")
# natalie = User.create(username: "natalie@natalie.com", first_name: "Natalie", last_name: "Nat", password: "n")
# david = User.create(username: "david@david.com", first_name: "David", last_name: "Dancing", password: "n")
# christina = User.create(username: "christina@christina.com", first_name: "Christina", last_name: "Komodo", password: "c")

# Create families:
woodwind = Family.create(name: "Woodwind")
string = Family.create(name: "String")
brass = Family.create(name: "Brass")
percussion = Family.create(name: "Percussion")
keyboard = Family.create(name: "Keyboard")
plucked = Family.create(name: "Plucked String")
voice = Family.create(name: "Vocal")
electric = Family.create(name: "Electronic")
intellect = Family.create(name: "Intellect")
other = Family.create(name: "Other")

# Create genres:
Genre.create(name: "Western Classical")
Genre.create(name: "Jazz")
Genre.create(name: "Symphonic")
Genre.create(name: "String Quartet")
Genre.create(name: "Chamber Ensemble")
Genre.create(name: "Contemporary Music")
Genre.create(name: "Pop")
Genre.create(name: "Texas Country")
Genre.create(name: "Country")
Genre.create(name: "Bluegrass")
Genre.create(name: "Zydeco")
Genre.create(name: "Dixiland")
Genre.create(name: "Rap")
Genre.create(name: "K-Pop")
Genre.create(name: "Rock")
Genre.create(name: "Indie Rock")
Genre.create(name: "Singer-songwriter")

#Create instruments:
Instrument.create(name: "Piccolo", family_id: woodwind.id)
Instrument.create(name: "Flute", family_id: woodwind.id)
ebclari = Instrument.create(name: "Eb Clarinet", family_id: woodwind.id)
bbclari = Instrument.create(name: "Bb Clarinet", family_id: woodwind.id)
aclari = Instrument.create(name: "A Clarinet", family_id: woodwind.id)
Instrument.create(name: "Bass Clarinet", family_id: woodwind.id)
Instrument.create(name: "Oboe", family_id: woodwind.id)
Instrument.create(name: "English Horn", family_id: woodwind.id)
Instrument.create(name: "Bassoon", family_id: woodwind.id)
Instrument.create(name: "Contra Bassoon", family_id: woodwind.id)
Instrument.create(name: "French Horn", family_id: brass.id)
Instrument.create(name: "Trumpet", family_id: brass.id)
Instrument.create(name: "Coronet", family_id: brass.id)
Instrument.create(name: "Trombone", family_id: brass.id)
Instrument.create(name: "Bass Trombone", family_id: brass.id)
Instrument.create(name: "Euphonium", family_id: brass.id)
Instrument.create(name: "Tuba", family_id: brass.id)
Instrument.create(name: "Violin", family_id: string.id)
Instrument.create(name: "Viola", family_id: string.id)
Instrument.create(name: "Cello", family_id: string.id)
Instrument.create(name: "Double Bass", family_id: string.id)
Instrument.create(name: "Timpani", family_id: percussion.id)
Instrument.create(name: "Drumset", family_id: percussion.id)
Instrument.create(name: "Orchestral Percussion", family_id: percussion.id)
Instrument.create(name: "Mallet Percussion", family_id: percussion.id)
Instrument.create(name: "Marimba", family_id: percussion.id)
Instrument.create(name: "Acoustic Guitar", family_id: plucked.id)
Instrument.create(name: "Electric Guitar", family_id: plucked.id)
Instrument.create(name: "Mandolin", family_id: plucked.id)
Instrument.create(name: "Banjo", family_id: plucked.id)
piano = Instrument.create(name: "Piano", family_id: keyboard.id)
Instrument.create(name: "Organ", family_id: keyboard.id)
Instrument.create(name: "Composer", family_id: intellect.id)
Instrument.create(name: "Conductor", family_id: intellect.id)
Instrument.create(name: "Voice", family_id: voice.id)
Instrument.create(name: "Soprano", family_id: voice.id)
Instrument.create(name: "Contralto", family_id: voice.id)
Instrument.create(name: "Tenor", family_id: voice.id)
Instrument.create(name: "Bass", family_id: voice.id)
Instrument.create(name: "Electric Bass", family_id: plucked.id)

# # # Add associations
# me = User.find_by(username: "annabush092@gmail.com")
# # # natalie = User.find_by(username: "natalie@natalie.com")
# david = User.find_by(username: "david@david.com")
# # # christina = User.find_by(username: "christina@christina.com")
# bbclari = Instrument.find_by(name: "Bb Clarinet")
# aclari = Instrument.find_by(name: "A Clarinet")
# classic = Genre.find_by(name: "Western Classical")
# symph = Genre.find_by(name: "Symphonic")
# piano = Instrument.find_by(name: "Piano")
# trombone = Instrument.find_by(name: "Trombone")
#
# me.update(instruments: [piano, bbclari, aclari])
# me.add_skill(bbclari, classic, true, true)
# me.add_skill(bbclari, symph, true, true)
# me.add_skill(aclari, symph, true, true)
# me.add_skill(aclari, classic, true, true)
# me.add_skill(piano, classic, true, false)
#
# david.update(instruments: [trombone])
# # #
# concert = Post.create(content: "Great concert last night!", user_id: 6)
# gig = Post.create(content: "Gig tonight in the west village- come check it out!", user_id: 7)
# trombone2 = Post.create(content: "Instrument stolen! Please look for my million dollar bass trombone!!", user_id: 8)
# trombone = Post.create(content: "Anyone know a good trombone?", user_id: 9)
# concert2 = Post.create(content: "Subbing in for the New York Phil tonight on Mahler's 5th!!", user_id: 6)
# jazz = Post.create(content: "La dee da dee da da boop beep blop I love jazz", user_id: 7)
# new_music = Post.create(content: "Boop boop beep bleep bloop what intellectual music", user_id: 8)
#
# tag1 = Tag.find_by(tag_text: "violin")
# tag2 = Tag.find_by(tag_text: "trombone")
# tag3 = Tag.find_by(tag_text: "new music")
# tag4 = Tag.find_by(tag_text: "jazz")
# tag5 = Tag.find_by(tag_text: "symphony")
# tag6 = Tag.find_by(tag_text: "gig")
#
# PostTag.create(post_id: concert.id, tag_id: tag6.id)
# PostTag.create(post_id: gig.id, tag_id: tag6.id)
# PostTag.create(post_id: trombone2.id, tag_id: tag2.id)
# PostTag.create(post_id: trombone.id, tag_id: tag2.id)
# PostTag.create(post_id: concert2.id, tag_id: tag6.id)
# PostTag.create(post_id: jazz.id, tag_id: tag4.id)
# PostTag.create(post_id: new_music.id, tag_id: tag3.id)
# PostTag.create(post_id: concert.id, tag_id: tag1.id)
# PostTag.create(post_id: concert2.id, tag_id: tag1.id)
# PostTag.create(post_id: concert2.id, tag_id: tag5.id)

# Post.all.each do |p|
#   p.update(created_at: Time.now)
# end

# User.all.each do |u|
#   u.update(picture_url: "http://www.limestone.edu/sites/default/files/user.png")
# end
#
# User.find_by(first_name: "Anna").update(picture_url: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAwaAAAAJDMyYjhjN2IxLWUwYzktNDEwMy04MmZmLWFkNDYzODFkN2NkMw.jpg")
# #
# User.find_by(first_name: "Robert").update(picture_url: "https://rlv.zcache.com/portrait_of_robert_schumann_square_sticker-r68c7e1a219924a5db99cb2b8ab91d326_v9wf3_8byvr_324.jpg")
#
# User.find_by(first_name: "Kenny").update(picture_url: "https://www.besteveralbums.com/albumart/album_large_12868_4e47f99ae7f76.jpg")
#
# User.find_by(first_name: "Blues").update(picture_url: "http://2.bp.blogspot.com/-5XkVgGWqKNc/T4eO2CMYKlI/AAAAAAAABa4/KLKm0TzK3js/s1600/btrav.jpg")
#
# User.find_by(first_name: "Bob").update(picture_url: "https://i.pinimg.com/736x/99/56/4a/99564a10ac35ce524ac95910c4c69e14--lp-covers-music-covers.jpg")
#
# User.find_by(first_name: "igor").update(picture_url: "https://cps-static.rovicorp.com/3/JPG_500/MI0000/986/MI0000986143.jpg?partner=allrovi.com")
#
# User.find_by(first_name: "Johannes").update(picture_url: "http://images.genius.com/4e152e28282d71ef3e064a39a4a94875.625x625x1.jpg")
#
# User.find_by(first_name: "Shosti").update(picture_url: "http://www.bach-cantatas.com/Pic-Lib-BIG/Shostakovich-Dmitri-103.jpg")
#
# User.find_by(first_name: "Ludwig von").update(picture_url: "https://www.biography.com/.image/t_share/MTI2NTgyMzIxOTcyMjU5NDU5/beethoven-600x600jpg.jpg")
